// <auto-generated />
using System;
using Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20240223201037_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID_BOOK");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("BOOK_NAME");
                    
                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("BOOK_AUTHOR");

                    b.Property<DateTime?>("BookPublication")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BOOK_PLUBLICATION");

                    b.Property<string>("Resume")
                        .HasColumnType("text")
                        .HasColumnName("BOOK_RESUME");

                    b.HasKey("Id");

                    b.ToTable("Book", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
